module.exports = {
  id: 'antinuke',
  name: 'Anti-Nuke',
  emoji: '🛡️',
  category: 'security',
  description: 'Protection anti-nuke avancée avec détection de mass actions, whitelist et mode urgence.',
  dependencies: [],
  requiredPermissions: ['Administrator'],
  configSchema: {
    enabled: { type: 'boolean', default: false },
    whitelistedUsers: { type: 'array', itemType: 'user', default: [] },
    whitelistedRoles: { type: 'array', itemType: 'role', default: [] },
    maxBansPerMinute: { type: 'number', default: 5 },
    maxKicksPerMinute: { type: 'number', default: 5 },
    maxChannelDeletesPerMinute: { type: 'number', default: 3 },
    maxRoleDeletesPerMinute: { type: 'number', default: 3 },
    maxChannelCreatesPerMinute: { type: 'number', default: 5 },
    maxRoleCreatesPerMinute: { type: 'number', default: 5 },
    maxWebhookCreatesPerMinute: { type: 'number', default: 3 },
    actionOnTrigger: { type: 'string', default: 'ban', enum: ['ban', 'kick', 'quarantine', 'derank'] },
    emergencyMode: { type: 'boolean', default: false },
    emergencyLockdown: { type: 'boolean', default: true },
    logChannelId: { type: 'channel', default: null },
    notifyOwner: { type: 'boolean', default: true },
    antiSelfbot: { type: 'boolean', default: false },
    antiMassJoin: { type: 'boolean', default: false },
    massJoinThreshold: { type: 'number', default: 10 },
    massJoinTimeWindow: { type: 'number', default: 10 },
  },
  commands: ['antinuke'],
  events: [
    'channelCreate', 'channelDelete', 'roleCreate', 'roleDelete',
    'guildBanAdd', 'guildMemberRemove', 'webhookUpdate',
  ],
  jobs: [],
};
