module.exports = {
  id: 'backup',
  name: 'Backup',
  emoji: '💾',
  category: 'admin',
  description: 'Système de sauvegarde et restauration complète du serveur et de la config bot.',
  dependencies: [],
  requiredPermissions: ['Administrator'],
  configSchema: {
    enabled: { type: 'boolean', default: true },
    autoBackup: { type: 'boolean', default: false },
    autoBackupInterval: { type: 'number', default: 86400000 },
    maxBackups: { type: 'number', default: 10 },
    includeMessages: { type: 'boolean', default: false },
    includeRoles: { type: 'boolean', default: true },
    includeChannels: { type: 'boolean', default: true },
    includeEmojis: { type: 'boolean', default: true },
    includeBans: { type: 'boolean', default: true },
    backupBotConfig: { type: 'boolean', default: true },
    notifyOnBackup: { type: 'boolean', default: true },
    notifyChannelId: { type: 'channel', default: null },
    encryptBackups: { type: 'boolean', default: false },
  },
  commands: ['backup'],
  events: [],
  jobs: ['autoBackupTask'],
};
