module.exports = {
  id: 'forums',
  name: 'Forums',
  emoji: '📋',
  category: 'utility',
  description: 'Gestion avancée des forums Discord avec auto-tags, templates et notifications.',
  dependencies: [],
  requiredPermissions: ['ManageChannels'],
  configSchema: {
    enabled: { type: 'boolean', default: true },
    forumConfigs: { type: 'array', default: [] },
    autoTagEnabled: { type: 'boolean', default: true },
    postTemplateEnabled: { type: 'boolean', default: true },
    autoReactEnabled: { type: 'boolean', default: false },
    autoReactEmojis: { type: 'string', default: '👍,👎' },
    notifyNewPosts: { type: 'boolean', default: false },
    notifyChannelId: { type: 'channel', default: null },
    autoArchiveDays: { type: 'number', default: 7 },
    resolvedTag: { type: 'string', default: 'Résolu' },
  },
  commands: ['forum'],
  events: ['threadCreate'],
  jobs: [],
};
