module.exports = {
  id: 'giveaway',
  name: 'Giveaways',
  emoji: '🎉',
  category: 'engagement',
  description: 'Système de giveaways complet avec conditions, bonus entries et récurrence.',
  dependencies: [],
  requiredPermissions: ['ManageGuild'],
  configSchema: {
    enabled: { type: 'boolean', default: true },
    managerRoles: { type: 'array', itemType: 'role', default: [] },
    defaultDuration: { type: 'number', default: 86400000 },
    maxDuration: { type: 'number', default: 2592000000 },
    maxWinners: { type: 'number', default: 20 },
    dmWinners: { type: 'boolean', default: true },
    autoRepost: { type: 'boolean', default: false },
    requireMinLevel: { type: 'number', default: 0 },
    requireMinMessages: { type: 'number', default: 0 },
    requireAccountAge: { type: 'number', default: 0 },
    bonusEntries: { type: 'object', default: {} },
    recurring: { type: 'boolean', default: false },
    endEmoji: { type: 'string', default: '🎊' },
    embedColor: { type: 'string', default: '#FF73FA' },
  },
  commands: ['giveaway'],
  events: [],
  jobs: ['giveawayEndTask'],
};
