module.exports = {
  id: 'polls',
  name: 'Sondages & Suggestions',
  emoji: '📊',
  category: 'engagement',
  description: 'Système de sondages et de suggestions avec votes et statuts.',
  dependencies: [],
  requiredPermissions: ['ManageMessages'],
  configSchema: {
    enabled: { type: 'boolean', default: true },
    pollsEnabled: { type: 'boolean', default: true },
    suggestionsEnabled: { type: 'boolean', default: true },
    suggestionsChannel: { type: 'channel', default: null },
    suggestionsResultChannel: { type: 'channel', default: null },
    anonymousVotes: { type: 'boolean', default: false },
    maxPollOptions: { type: 'number', default: 10 },
    maxPollDuration: { type: 'number', default: 604800000 },
    autoThread: { type: 'boolean', default: false },
    upvoteEmoji: { type: 'string', default: '👍' },
    downvoteEmoji: { type: 'string', default: '👎' },
    staffRoles: { type: 'array', itemType: 'role', default: [] },
    embedColor: { type: 'string', default: '#3498DB' },
  },
  commands: ['poll', 'suggest'],
  events: [],
  jobs: ['pollEndTask'],
};
