module.exports = {
  id: 'social',
  name: 'Social & Profils',
  emoji: '👤',
  category: 'social',
  description: 'Profils personnalisables, réputation, mariage, anniversaires et badges.',
  dependencies: [],
  requiredPermissions: [],
  configSchema: {
    enabled: { type: 'boolean', default: true },
    profileEnabled: { type: 'boolean', default: true },
    reputationEnabled: { type: 'boolean', default: true },
    reputationCooldown: { type: 'number', default: 86400000 },
    marriageEnabled: { type: 'boolean', default: true },
    divorceEnabled: { type: 'boolean', default: true },
    birthdayEnabled: { type: 'boolean', default: true },
    birthdayChannel: { type: 'channel', default: null },
    birthdayRole: { type: 'role', default: null },
    birthdayMessage: { type: 'string', default: '🎂 Joyeux anniversaire à {user} !' },
    badgesEnabled: { type: 'boolean', default: true },
    customBackgrounds: { type: 'boolean', default: true },
    embedColor: { type: 'string', default: '#E91E63' },
  },
  commands: ['profile', 'reputation', 'marry', 'birthday'],
  events: [],
  jobs: ['birthdayTask'],
};
