module.exports = {
  id: 'verify',
  name: 'Vérification',
  emoji: '✅',
  category: 'security',
  description: 'Système de vérification des nouveaux membres (bouton, captcha, questions, règlement).',
  dependencies: [],
  requiredPermissions: ['ManageRoles'],
  configSchema: {
    enabled: { type: 'boolean', default: true },
    type: { type: 'string', default: 'button', enum: ['button', 'reaction', 'captcha', 'question', 'rules'] },
    channelId: { type: 'channel', default: null },
    verifiedRoleId: { type: 'role', default: null },
    unverifiedRoleId: { type: 'role', default: null },
    timeoutMinutes: { type: 'number', default: 30 },
    minAccountAgeDays: { type: 'number', default: 0 },
    question: { type: 'string', default: '' },
    answer: { type: 'string', default: '' },
    rulesText: { type: 'string', default: '' },
    dmWelcome: { type: 'boolean', default: false },
    dmMessage: { type: 'string', default: 'Bienvenue ! Vous avez été vérifié.' },
    logChannel: { type: 'channel', default: null },
  },
  commands: ['verify'],
  events: ['guildMemberAdd'],
  jobs: ['verifyTimeoutTask'],
};
